name: Test on Pull Request

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest tests
      - name: Check test results
        run: |
          if pytest tests --junitxml=test-results.xml ; then
            echo "All tests passed!"
            exit 0
          else
            echo "Tests failed!"
            exit 1
          fi